server {
    listen 443 ssl;
    server_name newssummaryhelper.aryhsg.com;

    root /usr/share/nginx/html;

    index main3.html index.html;

    ssl_certificate /etc/nginx/ssl/newsbot.pem;
    ssl_certificate_key /etc/nginx/ssl/newsbot.key;    

    location / {
        # 嘗試尋找檔案，若找不到則回傳 404
        # 如果你未來改用 React 路由，這裡要改為 /index.html
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80 default_server;
    listen 443 ssl default_server;
    
    server_name _;

    ssl_certificate /etc/nginx/ssl/newsbot.pem;
    ssl_certificate_key /etc/nginx/ssl/newsbot.key;

    return 444;
}

# LINE Bot 服務 (5000 埠)
server {
    listen 443 ssl;
    server_name newsbot.aryhsg.com;

    ssl_certificate /etc/nginx/ssl/newsbot.pem;
    ssl_certificate_key /etc/nginx/ssl/newsbot.key;

    location / {
        proxy_pass http://line:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# HTTP 強制跳轉 HTTPS (選配，建議加上)
server {
    listen 80;
    server_name newsbot.aryhsg.com newsapi.aryhsg.com;
    return 301 https://$host$request_uri;
}
